version: '3.7'

services:
  hydra:
    image: oryd/hydra:v1.10.1
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http --dangerous-allow-insecure-redirect-urls=192.168.1.112,127.0.0.1,0.0.0.0,localhost
    volumes:
      - type: bind
        source: ./contrib/quickstart/hydra/5-min
        target: /etc/config/hydra
    environment:
      - DSN=mysql://root:secret@tcp(mysqld:3306)/hydra?max_conns=20&max_idle_conns=4
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=true
      - LOG_LEAK_SENSITIVE_VALUES=true
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=*
      - SERVE_PUBLIC_CORS_ENABLED=true
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v1.10.1
    environment:
      - DSN=mysql://root:secret@tcp(mysqld:3306)/hydra?max_conns=20&max_idle_conns=4
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    depends_on:
      - mysqld
    volumes:
      - type: bind
        source: ./contrib/quickstart/hydra/5-min
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet
#
#  consent:
#    environment:
#      - HYDRA_ADMIN_URL=http://192.168.1.112:4445
#    image: oryd/hydra-login-consent-node:v1.10.1
#    ports:
#      - "3000:3000"
#    restart: unless-stopped
#    networks:
#      - intranet

networks:
  intranet:
